url: "https://observatoriodeegressos.github.io" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "/guia-egressos" # the subpath of your site, e.g. /blog

title: "Guia PNP Evasão da RFEPCT - Indicadores" # Nome do sistema ou plataforma
subtitle: "" #Órgão ou entidade
sign: "" # Assinatura
footer: "Documentação elaborada pela Secretaria de Educação Profissional e Tecnológica (SETEC) / Página desenvolvida pela Rede DSBR."
menu: "Todo o conteúdo deste site está publicado sob a licença MIT."
search_engine: "lunrjs" # Valores possíveis serão "lunrjs", "google". Outro valor irá desativar.
share_buttons: true

plugins: []
